mroc_admin_homepage:
    path: /
    defaults: { _controller: MROCAdminBundle:Default:index }

mroc_admin_csv:
    path: /csv
    defaults: { _controller: MROCAdminBundle:Default:importCSV }

mroc_admin_images:
    path: /images
    defaults: { _controller: MROCAdminBundle:Default:images }

MROCAdminBundle_object:
    resource: "@MROCAdminBundle/Resources/config/routing/object.yml"
    prefix:   /object

MROCAdminBundle_object_type:
    resource: "@MROCAdminBundle/Resources/config/routing/objecttype.yml"
    prefix:   /object_type

MROCAdminBundle_sale_type:
    resource: "@MROCAdminBundle/Resources/config/routing/saletype.yml"
    prefix:   /sale_type