mroc_admin_homepage:
    path: /
    defaults: { _controller: MROCAdminBundle:Default:index }

mroc_admin_csv:
    path: /csv
    defaults: { _controller: MROCAdminBundle:Default:importCSV }

mroc_admin_images:
    path: /images
    defaults: { _controller: MROCAdminBundle:Default:images }

mroc_admin_complaints:
    path: /complaints
    defaults: { _controller: MROCAdminBundle:Default:complaintList, page:0 }

mroc_admin_object_complaints:
    path: /object_complaints_list
    defaults: { _controller: MROCAdminBundle:Default:objectComplaintList, page:0 }

mroc_admin_comments:
    path: /comments
    defaults: { _controller: MROCAdminBundle:Default:commentList, page:0 }

mroc_admin_comment_approve:
    path: /comments/approve/{id}
    defaults: { _controller: MROCAdminBundle:Default:commentApprove }

mroc_admin_register_owner:
    path: /owner_register
    defaults: { _controller: MROCAdminBundle:Default:registerOwner }

mroc_admin_user_list:
    path: /users
    defaults: { _controller: MROCAdminBundle:Default:users, page:0 }

MROCAdminBundle_owner:
    resource: "@MROCAdminBundle/Resources/config/routing/owner.yml"
    prefix:   /owner

MROCAdminBundle_object:
    resource: "@MROCAdminBundle/Resources/config/routing/object.yml"
    prefix:   /object

MROCAdminBundle_object_type:
    resource: "@MROCAdminBundle/Resources/config/routing/objecttype.yml"
    prefix:   /object_type

MROCAdminBundle_sale_type:
    resource: "@MROCAdminBundle/Resources/config/routing/saletype.yml"
    prefix:   /sale_type