mroc_main_homepage:
    path:     /
    defaults: { _controller: MROCMainBundle:Default:index }

mroc_main_homepage_mobile:
    path:     /mobile
    defaults: { _controller: MROCMainBundle:Default:mobileIndex }

_xhr_mroc_main_get_extended_info:
    path: /extended
    defaults: { _controller: MROCMainBundle:Default:getExtended }

_xhr_mroc_main_modify_rating:
    path: /rating
    defaults: { _controller: MROCMainBundle:Default:modifyRating }

_xhr_mroc_main_complaint:
    path: /complaint
    defaults: { _controller: MROCMainBundle:Default:complaint }

_xhr_mroc_main_question:
    path: /question
    defaults: { _controller: MROCMainBundle:Default:question }