mroc_main_homepage:
    path:     /
    defaults: { _controller: MROCMainBundle:Default:index }

mroc_main_homepage_mobile:
    path:     /mobile
    defaults: { _controller: MROCMainBundle:Default:mobileIndex }

mroc_main_get_extended_info:
    path: /extended
    defaults: { _controller: MROCMainBundle:Default:getExtended }