parameters:
#    mroc_main.example.class: MROC\MainBundle\Example

services:
#    mroc_main.example:
#        class: %mroc_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
