<?php

namespace MROC\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends EntityRepository
{
    public function getIdAddressList()
    {
        $em = $this->getEntityManager();
        $q = $em->createQueryBuilder()->select('n.coordinates','n.id')
            ->from('MROCMainBundle:Object','n')
            ->getQuery();
        $result = $q->getResult();

        foreach($result as $k=>$v){
            $result[$k]['coordinates'] = explode(' ',$v['coordinates']);
            $result[$k]['coordinates'] = array_reverse($result[$k]['coordinates']);
        }
        return $result;
    }


}
