<?php

namespace MROC\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectComplaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectComplaintRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function getElementsCount()
    {
        $em = $this->getEntityManager();
        $query = $em->getConnection()->prepare('select count(*) as count from '.$this->getClassMetadata()->getTableName());
        $query->execute();
        $st = $query->fetch();
        return $st['count'];
    }
}
