<?php

namespace MROC\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends EntityRepository
{

    public function getIdAddressList($land_missing_color,$default_color)
    {
        $em = $this->getEntityManager();
        $q = $em->createQueryBuilder()->select('n.coordinates','n.id','t.color','t.id as ot','IDENTITY(n.sale_type) as st','n.registered_land')
            ->from('MROCMainBundle:Object','n')
            ->leftJoin('MROCMainBundle:ObjectType','t','WITH','n.object_type = t.id')
            ->getQuery();
        $result = $q->getResult(); $data = array();

        foreach($result as $k=>$v){
            $data[$v['id']]['coordinates'] = explode(' ',$v['coordinates']);
            $data[$v['id']]['coordinates'] = array_reverse($data[$v['id']]['coordinates']);
            $data[$v['id']]['ot'] = $v['ot'];
            $data[$v['id']]['st'] = $v['st'];
            if($v['registered_land']){
                if($v['color']){
                    $data[$v['id']]['color'] = $v['color'];
                }else{
                    $data[$v['id']]['color'] = $default_color;
                }
            }else{
                $data[$v['id']]['color'] = $land_missing_color;
            }
        }
        return $data;
    }

    public function getTop($n = 5)
    {
        $em = $this->getEntityManager();
        $q = $em->createQueryBuilder()->select('n')
            ->from('MROCMainBundle:Object','n')
            ->orderBy('n.rating','desc')
            ->setMaxResults($n)
            ->getQuery();

        $result = $q->getResult();
        return $result;
    }

    /**
     * @return mixed
     */
    public function getElementsCount()
    {
        $em = $this->getEntityManager();
        $query = $em->getConnection()->prepare('select count(*) as count from '.$this->getClassMetadata()->getTableName());
        $query->execute();
        $st = $query->fetch();
        return $st['count'];
    }

    /**
     * @param $node Object
     * @return array
     */
    public function getRank($node)
    {
        $em = $this->getEntityManager();
        $t_name = $em->getClassMetadata($this->getClassName())->getTableName();

        $q = $em->getConnection()->prepare('select z.rank from (select t.id, t.rating, @rownum := @rownum + 1 as rank from '.$t_name.' t, (select @rownum :=0) r order by rating desc) as z where id = :id');
        $q->bindValue(':id',$node->getId());
        $q->execute();

        $result = $q->fetch();
        return $result['rank'];
    }


}
