object_type:
    path:     /list
    defaults: { _controller: "MROCAdminBundle:ObjectType:index" }

object_type_new:
    path:     /new
    defaults: { _controller: "MROCAdminBundle:ObjectType:new" }

object_type_create:
    path:     /create
    defaults: { _controller: "MROCAdminBundle:ObjectType:create" }
    requirements: { _method: post }

object_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "MROCAdminBundle:ObjectType:edit" }

object_type_update:
    path:     /{id}/update
    defaults: { _controller: "MROCAdminBundle:ObjectType:update" }
    requirements: { _method: post|put }

object_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "MROCAdminBundle:ObjectType:delete" }