sale_type:
    path:     /list
    defaults: { _controller: "MROCAdminBundle:SaleType:index" }

sale_type_show:
    path:     /{id}/show
    defaults: { _controller: "MROCAdminBundle:SaleType:show" }

sale_type_new:
    path:     /new
    defaults: { _controller: "MROCAdminBundle:SaleType:new" }

sale_type_create:
    path:     /create
    defaults: { _controller: "MROCAdminBundle:SaleType:create" }
    requirements: { _method: post }

sale_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "MROCAdminBundle:SaleType:edit" }

sale_type_update:
    path:     /{id}/update
    defaults: { _controller: "MROCAdminBundle:SaleType:update" }
    requirements: { _method: post|put }

sale_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "MROCAdminBundle:SaleType:delete" }
    requirements: { _method: post|delete }
