parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     mroc
    database_user:     root
    database_password: matrixx1s

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            ru
    secret:            ThisTokenIsNotSoSecretChangeIt

    debug_toolbar:          false
    debug_redirects:        false
    use_assetic_controller: false

    complaint_email: golikanu@yandex.ru

    color.land_missing: '#ffff00'
    color.default: '#0e53a7'
