mroc_admin:
    resource: "@MROCAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

mroc_main:
    resource: "@MROCMainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
